### ISSUE TITLE
Find or create and add application icon

### ISSUE THREAD

**Issue by tarasn** [tarasn/MassTranslator#1]

**Comment by OrderAndCh4oS** [comment]
Are you looking for a logo for the application icon?

**Comment by tarasn** [comment]
Yes. You can create a simple logo for the application.

**Comment by OrderAndCh4oS** [comment]
Sure what sort of thing did you have in mind? Anything to go on would be a great help. 

I'm not exactly clear on what it is that you are translating, could you tell me a little more about the app, we could also add a description to the README

**Comment by tarasn** [comment]
This application can be used to translate specially formatted XML files.The XML contains translated entries that will be shown to end user on Google Play Market .  In addition - the app can  translate text from one language to another. Mass Translator uses google translation service.

**Comment by OrderAndCh4oS** [comment]
Great, I'll see what I can come up with, do you have specific sizes/formats for the icon? Will an SVG be ok?
